---
title: "Papers & Presentations"
output:
  tufte::tufte_html : default
---

# _Early Presentations_ #

## <u>Jouissance - A Clinical Case Study</u> ##
### Jade, 03.01.2022 ###

This was the first presentation of the group, where Jade tried to approach the difficult concept of jouissance by the help of a clinical example. The recordings aren't available but the slides are linked below:

[Slides](papers/early/jade-jouissance.pptx)

## <u>Transference Focused Psychotherapy : An Introduction</u> ##
### Sean, 07.01.2022 ###

Sean summarised the findings of Kernberg, et.al and their treatment of patients with Borderline Personality Disorder through a revised object-relations approach. The main paper that was of reference in this presentation was: 

Otto F. Kernberg, Frank E. Yeomans, John F. Clarkin & Kenneth N. Levy. (2008) *Transference focused psychotherapy: Overview and update*, The International Journal of Psychoanalysis, 89:3, 601-620, DOI: 10.1111/j.1745-8315.2008.00046.x

## <u>Beyond Thinking, Speaking and Dreaming : The Analytic Process of Psychoanalysis</u> ##
### Divya Ranjan, 17.01.2022 ###

This was first of three presentation in a series by Divya on some of the "foundations" in psychoanalysis. This was devoted to the subject of *analytic process* and introduces other things from scratch. The latter half of the presentation uses a case study from Ogden's work.

[Slides](papers/early/divya-analytic-process.pdf)

## <u>A Fairbairnian Approach to the Therapeutic Relationship</u>##
### Sean, 07.02.2022 ###

This presentation was a "return to Fairbairn" to extract from his theory several insights important for therapeutic purposes. Sean follows the work of David Celani in his book *Object Relations in the Clinical Setting*. 

##<u>Speech, Suffering and Ambivalence : Importance of Speech in Analysis</u>##
### Divya, 14.02.2022 ###

This was a follow-up presentation to my last presentation on the analytic process. This was quite a scattered talk, but nonetheless the main points regarding the importance of speech were made along with a short clinical vignette which emphasises the importance of speech when problematic things like ambivalence and mourning during analysis. The audio of the recording is available below:

[Audio](recordings/divya-speech.aac)

##<u>Analytic Waves : On Transference</u>###
###Divya, Jade, 22.02.2022###

This was a joint presentation as a continuation from the last presentation to address one of the fundamental concepts in psychoanalysis: transference. I (Divya) trace out a bit of history and theoretical part of the presentation before Jade comes in to explain what transference might look like in the clinic by a case vignette from Estella Welldon's *Dancing With Death* (2009). 

YT Link
[Slides](papers/early/divya-jade-transference.pdf)

# Seminars on Anxiety #

This was a joint venture in trying to approach the heavy concept of anxiety from differing schools of psychoanalysis. This is the first of many topics that we'd be covering in future, the goal is to make dialogue happen across people coming from different theoretical/clinical backgrounds in psychoanalysis. They write a paper or prepare a presentation and then we allow for open-ended discussion to happen.

##Anxiety and Its Vicissitudes##

###Divya, 05.03.2022###

This was first in a series of presentations devoted to the concept of anxiety in psychoanalysis. In the following presentation I (Divya) tried to trace the historical development of anxiety in psychoanalysis from Freud till Abraham and then introduce the novel contributions made by Klein. Attached below is the paper and the recording of the presentation. 

[Paper](papers/anxiety/divya-anxiety.pdf)

##Thinking Anxiety in Clinic With Roussillon##
###Jade, 12.03.2022###

This was the second in the series of seminars on anxiety. Here Jade takes a heavily clinical approach to understanding anxiety, amidst the heavy and confusing theory that exists in Lacanian psychoanalysis for the given subject. He uses Roussillon's methods from his manual on psychopathology. Below is the attached paper with the presentation slides and recording.

[Slides](papers/anxiety/jado-anxiety.pptx)
[Paper](papers/anxiety/jado-anxiety.docx)




